import json
import time
import uuid

"""Local stand-in for the Forjinn LLM, used both by the /api/mock-predict
route (for external/test callers) and, more importantly, as the in-process
fallback whenever PREDICTION_URL is unreachable. Living in its own module
(rather than inside app.py or routes/projects.py) lets every fallback call
site invoke it as a plain function call instead of an HTTP request back into
the same server — an HTTP loopback would need a free worker thread from the
same pool that's already exhausted by the failing upstream call, which is
exactly the self-deadlock this avoids."""


def build_mock_response_text(question_prompt: str) -> str:
    """Non-streaming mock LLM response, pattern-matched on prompt content."""
    if "Precise data extraction agent" in question_prompt or "precise data extraction agent" in question_prompt.lower():
        # Delta extraction
        if "Retail Logistics System" in question_prompt:
            return json.dumps({
                "project_name": "Retail Logistics System",
                "department": "Logistics",
                "business_unit": "PES",
                "timeline": "6 Months",
                "description": "Automated warehouse logistics system."
            })
        return json.dumps({
            "project_name": "Validation Project",
            "department": "Engineering"
        })
    elif "fresh, unified, and cohesive requirements summary" in question_prompt.lower():
        # Summary
        return "This is a cohesive requirements summary generated by the rolling summarization service."
    elif "expert business analyst" in question_prompt.lower() or "compile this into a comprehensive" in question_prompt.lower():
        # Doc compilation
        return (
            "# Final Discovery Requirements - Validation Project\n\n"
            "## 1. Project Overview\n"
            "This is a compiled document of project requirements.\n\n"
            "## 2. Business Problem & Goals\n"
            "- Goal 1: Improve efficiency.\n\n"
            "## 3. Functional Requirements\n"
            "- FR-1: Real-time GPS tracking (High Priority)\n"
            "- FR-2: Automated dispatch notifications (Medium Priority)\n"
        )
    return "Mock non-streaming response from local BA-Bot server."


def generate_mock_stream_lines():
    """Yields raw SSE 'data: {...}' lines identical to what /api/mock-predict
    streams over HTTP."""
    tokens = [
        "Hello! ", "This ", "is ", "a ", "locally ", "generated ", "mock ", "response ",
        "from ", "the ", "BA-Bot ", "service. ", "Your ", "containerized ", "deployment ",
        "is ", "fully ", "operational ", "and ", "independent ", "of ", "external ",
        "dependencies."
    ]
    for token in tokens:
        chunk = {"event": "token", "data": token}
        yield f"data: {json.dumps(chunk)}"
        time.sleep(0.02)

    chat_id = f"session-{uuid.uuid4()}"
    metadata_chunk = {
        "event": "metadata",
        "data": {"chatId": chat_id, "sessionId": chat_id}
    }
    yield f"data: {json.dumps(metadata_chunk)}"
