import React, { useState, useEffect } from 'react';

interface DocumentData {
  id: number;
  project_id: number;
  project_name: string;
  action: string;
  format: string;
  triggered_by: string;
  timestamp: string;
}

interface DocumentsPanelProps {
  token: string;
}

const DocumentsPanel: React.FC<DocumentsPanelProps> = ({ token }) => {
  const [documents, setDocuments] = useState<DocumentData[]>([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState('');
  const [formatFilter, setFormatFilter] = useState('');

  const fetchDocuments = async () => {
    setLoading(true);
    try {
      const res = await fetch('http://127.0.0.1:8000/api/admin/documents', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        setDocuments(data);
      }
    } catch (err) {
      console.error('Failed to load documents list', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void fetchDocuments();
  }, [token]);

  const handleDownload = async (projectId: number, format: string, projectName: string) => {
    try {
      const formatParam = format.toLowerCase() === 'docx' ? 'word' : 'pdf';
      const res = await fetch(`http://127.0.0.1:8000/api/projects/${projectId}/export?format=${formatParam}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (!res.ok) {
        throw new Error('Export request failed');
      }
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const slug = projectName.replace(/\s+/g, '_');
      a.download = `${slug}_requirements.${format.toLowerCase()}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Error downloading document', err);
      alert('Failed to retrieve and download this requirements compile.');
    }
  };

  const filtered = documents.filter(d => {
    const matchesSearch = d.project_name.toLowerCase().includes(search.toLowerCase()) ||
                          d.triggered_by.toLowerCase().includes(search.toLowerCase());
    const matchesFormat = !formatFilter || d.format === formatFilter;
    return matchesSearch && matchesFormat;
  });

  return (
    <div>
      <div className="admin-header-row">
        <h1>Exported Documents Catalog</h1>
        <p>View, manage, and download compliance specifications generated by system users.</p>
      </div>

      {/* FILTER BAR */}
      <div className="filters-card">
        <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap', width: '100%' }}>
          <div style={{ flex: '1', minWidth: '240px' }}>
            <input
              type="text"
              placeholder="Search by project name or user email..."
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="search-input"
              style={{ width: '100%', padding: '10px 14px', borderRadius: '8px', border: '1px solid #cbd5e1' }}
            />
          </div>
          <div style={{ width: '160px' }}>
            <select
              value={formatFilter}
              onChange={e => setFormatFilter(e.target.value)}
              style={{ width: '100%', padding: '10px 12px', borderRadius: '8px', border: '1px solid #cbd5e1', cursor: 'pointer', height: '42px', backgroundColor: '#fff' }}
            >
              <option value="">All Formats</option>
              <option value="PDF">PDF</option>
              <option value="DOCX">DOCX</option>
            </select>
          </div>
        </div>
      </div>

      {/* DOCUMENTS TABLE */}
      <div className="table-card" style={{ marginTop: '20px' }}>
        {loading ? (
          <div className="skeleton-container">
            <div className="skeleton-row" style={{ height: '45px' }} />
            <div className="skeleton-row" />
            <div className="skeleton-row" />
          </div>
        ) : filtered.length === 0 ? (
          <div className="empty-state" style={{ padding: '50px 20px' }}>
            <div style={{ fontSize: '3.5rem', marginBottom: '16px' }}>📄</div>
            <h3>No Documents Found</h3>
            <p>Exported project specifications will be listed here.</p>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table className="admin-table">
              <thead>
                <tr>
                  <th>Project Workspace</th>
                  <th>Compliance Format</th>
                  <th>Logged Action</th>
                  <th>Triggered By</th>
                  <th>Compiled At</th>
                  <th style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map(d => (
                  <tr key={d.id}>
                    <td>
                      <span style={{ fontWeight: '600', color: '#0f172a' }}>{d.project_name}</span>
                    </td>
                    <td>
                      <span style={{
                        padding: '3px 8px',
                        borderRadius: '4px',
                        background: d.format === 'PDF' ? '#fee2e2' : '#dbeafe',
                        color: d.format === 'PDF' ? '#991b1b' : '#1e40af',
                        fontWeight: 'bold',
                        fontSize: '0.75rem'
                      }}>
                        {d.format}
                      </span>
                    </td>
                    <td>{d.action}</td>
                    <td>{d.triggered_by}</td>
                    <td>{new Date(d.timestamp).toLocaleString()}</td>
                    <td style={{ textAlign: 'right' }}>
                      <button
                        className="admin-btn secondary small"
                        onClick={() => handleDownload(d.project_id, d.format, d.project_name)}
                      >
                        ⬇️ Download File
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default DocumentsPanel;
